[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "s"
panic = "abort"
strip = "symbols"

[workspace]
members = [".", "crates/*"]

[package]
name = "prometheus"
version = "0.5.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
