name: Create Release Branch

on:
  release:
    types: [prereleased]

defaults:
  run:
    shell: bash

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Determine release branch name
        id: branch_name
        run: echo "::set-output name=branch_name::release-${GITHUB_REF##*/}"

      - name: Create and switch to the new branch
        run: git checkout -b ${{ steps.branch_name.outputs.branch_name }}

      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update Cargo.toml version
        run: |
          # Update the Cargo.toml version using sed
          # For Linux
          sed -i "s/^version = \".*\"$/version = \"${VERSION}\"/" Cargo.toml

          # Update lockfile
          cargo generate-lockfile

      - name: Commit changes
        run: |
          git add Cargo.toml Cargo.lock
          git commit -m "Update Cargo.toml version to ${VERSION}"

      - name: Push the new branch
        run: git push origin ${{ steps.branch_name.outputs.branch_name }}

      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh

      - name: Create Pull Request
        run: |
          gh pr create \
            --title "Release ${VERSION}" \
            --body "This PR updates the version in Cargo.toml to ${VERSION}." \
            --base main \
            --head ${{ steps.branch_name.outputs.branch_name }}
